### ISSUE TITLE
Website Interface Node 

### ISSUE THREAD

**Issue by Justin-Prasad** [UBCSailbot/local_pathfinding#62]
### Purpose

We want to publish local pathfinding data to the website for visualization and debugging

### Description

- In node_navigate.py we want to publish to LPath Data (add to the node_navigate python file). 
- Want to create a publisher, its timer, and callback function 
- In the callback function, want to initialize a message of type LPath Data, initialize its variables, and publish it
- Covert LocalPath.waypoints (Found in LocalPath) to be published as a LPath Data message
- LocalPath is an instance variable of node_navigate, so to get LocalPath we need to do self.local_path

### Resources

- LPath data is documented here: https://github.com/UBCSailbot/custom_interfaces
- LPath Data message: https://github.com/UBCSailbot/custom_interfaces/blob/main/msg/LPathData.msg
- Local Path Defintion: https://github.com/UBCSailbot/local_pathfinding/blob/main/local_pathfinding/local_path.py
- Node_navigate Node: https://github.com/UBCSailbot/local_pathfinding/blob/main/local_pathfinding/node_navigate.py
    - Use desired heading publisher as reference. Infrastructure-wise, it should be identical so just do this for LPath Data

**Comment by jamenkaye** [comment]
Hi Justin, nice work making this issue! Eventually someone will need to add collision zones for AIS ships to be published here too, but I'll make a separate issue for that :)
