### ISSUE TITLE
Mock Global Path Part 2: WEB & NET

### ISSUE THREAD

**Issue by SPDonaghy** [UBCSailbot/local_pathfinding#69]
### Purpose

This is the second part to the global path module implementation (the right side of the diagram below)
### Description

This Global Path Module will receive the global path from WEB via POST request and then send it via POST to the Remote Transceiver.
Some features may overlap with the part one module, and the two modules may be combined at a later time.

### Resources
General structure of parts 1 and 2 of the mock global path implementation.

![image](https://github.com/UBCSailbot/local_pathfinding/assets/118148642/56da1afc-4076-488e-a291-b77fcd48f775)

**Comment by patrick-5546** [comment]
Better diagram

![image](https://github.com/UBCSailbot/local_pathfinding/assets/65756895/f1d644f5-74e6-45a9-a8ca-f6147716f23e)

**Comment by SPDonaghy** [comment]
GPS URL: http://localhost:3005/api/gps
Global Path Endpoint: http://localhost:8081/global-path

**Comment by patrick-5546** [comment]
Another one

![image](https://github.com/UBCSailbot/local_pathfinding/assets/65756895/f82a1b31-ead2-4ab0-b51c-28d81ae51f2b)

**Comment by patrick-5546** [comment]
A new new diagram to discuss in the soft-wide meeting

<img width="706" alt="image" src="https://github.com/UBCSailbot/local_pathfinding/assets/65756895/eee47c45-738e-4950-96da-9b9d78bf6fea">
