### ISSUE TITLE
Migrate Python Dependencies for ROS Specific Functionalities from Docker Image to package.xml

### ISSUE THREAD

**Issue by SPDonaghy** [UBCSailbot/local_pathfinding#89]
### Purpose

We want to distinguish between dependencies that are required by our ROS nodes and those which are not.

For example: 

**NumPy** is used by some of our ROS nodes so we will specify that dependency in the package.xml file, ensuring that dependency is built into the package.

**Flask** is used for creating mock global paths and is not involved with any ROS processes, so the dependency is specified in the Docker image.

### Changes

Moving any dependencies, for ROS nodes in the local_pathfinding package, from the base-dev.Dockerfile to the package.xml file.

### Resources

- [Sailbot Workspace Parent Issue](https://github.com/UBCSailbot/sailbot_workspace/issues/242)

**Comment by patrick-5546** [comment]
Just forgot to link to pr
